//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportVehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportVehicle()
        {
            this.DriverTransportVehicles = new HashSet<DriverTransportVehicle>();
        }
    
        public int IdTransportVehicle { get; set; }
        public string VIN { get; set; }
        public int EngineId { get; set; }
        public int ColorId { get; set; }
        public int TypeOfTransportVehicle { get; set; }
        public int InsuranceId { get; set; }
    
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverTransportVehicle> DriverTransportVehicles { get; set; }
        public virtual Engine Engine { get; set; }
        public virtual Insurance Insurance { get; set; }
        public virtual TypeOfTransportVehicle TypeOfTransportVehicle1 { get; set; }
    }
}
